### ISSUE TITLE
Why does README.md tell people to clone from a different private repo?

### ISSUE THREAD

**Issue by wikked1** [heapwolf/ldb#63]
Why does README.md point to `github.com/**0x00a**/ldb.git`?  Shouldn't it be `github.com/**hxoht**/ldb.git`?

The 0x00a looks strange and is not explained anywhere.  It should at least be explained. The user 0x00a does not appear to be a contributor to this project, and his (I assume?) fork of the project is not public.  Given that the official LevelDB homepage (http://leveldb.org) links to **this** project (the project under which I am posting this issue), I think this should be cleaned up or explained, because it looks potentially untrustworthy.

**Comment by heapwolf** [comment]
Fixed in 6e492efb30c05ef07090a86fa54d20ef7dcc4b71.
